// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNhZokhadvPjurh9q9Dm5CNM5tTLpt15o',
    appId: '1:192071818744:web:6bb93ab215d9416a1f0a0d',
    messagingSenderId: '192071818744',
    projectId: 'enono-b5cfa',
    authDomain: 'enono-b5cfa.firebaseapp.com',
    storageBucket: 'enono-b5cfa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Mb2HC0wDW1aRpCueG1KWHMsUQ04k7Vg',
    appId: '1:192071818744:android:74297cc6e81eb4a81f0a0d',
    messagingSenderId: '192071818744',
    projectId: 'enono-b5cfa',
    storageBucket: 'enono-b5cfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-UFVcd7JhLTS5FcynAa-JZS4C1CddHoY',
    appId: '1:192071818744:ios:e12e0cb854fd2a671f0a0d',
    messagingSenderId: '192071818744',
    projectId: 'enono-b5cfa',
    storageBucket: 'enono-b5cfa.appspot.com',
    iosClientId: '192071818744-cuvdj6jikga4n1jlfv4d0stm6rfpo54d.apps.googleusercontent.com',
    iosBundleId: 'com.example.enono',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-UFVcd7JhLTS5FcynAa-JZS4C1CddHoY',
    appId: '1:192071818744:ios:e12e0cb854fd2a671f0a0d',
    messagingSenderId: '192071818744',
    projectId: 'enono-b5cfa',
    storageBucket: 'enono-b5cfa.appspot.com',
    iosClientId: '192071818744-cuvdj6jikga4n1jlfv4d0stm6rfpo54d.apps.googleusercontent.com',
    iosBundleId: 'com.example.enono',
  );
}
